### PR TITLE
Fixes with key pressing, colors. More info in messages

### PR DESCRIPTION
**Pull request by 7yber**
Some improvements with key pressing (no needs in Enter key). Service messages were colorized. Added header to analyze boot message. Disclosed info about started, stopped, enabled and disabled services.

### CODE REVIEW

**Comment by 7yber** [comment]
Hm...Font size checking in appearance-menu. :) I will try to implement it this evening.

**Comment by 7yber** [comment]
Next target will be diclosing info about current active themes. Now I work on excluding unpredictable situations and messages.

**Comment by 7yber** [comment]
And return command should be added to all functions. Like `return STATUSVAR` it makes code more clear for understanding.

**Comment by Chrysostomus** [comment]
Looks promising. I'll need to merge these manually because of the conflicts.

**Comment by 7yber** [comment]
Hm, maybe. I'm not well in github.

**Comment by 7yber** [comment]
Font size checking done

**Comment by Chrysostomus** [comment]
Okay, I implemented your changes manually and added font sorting.

**Comment by 7yber** [comment]
Hm, some problems with pull request. New fixed files: appearance-menu, bmenu, initmenu, system-settings. How to pull them in good way?

**Pull request closed without merging**
